version: "3.8"
services:
  dcs-postgres:
    image: postgres:15.3-alpine
    container_name: nexer-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: nexer
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

  app:
    build:
      context: .
      dockerfile: ./src/Nexer.Finance.Application/Dockerfile
    container_name: nexer-app
    restart: always
    ports:
      - 8080:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - dcs-postgres

networks:
  default:
    name: local-network
